name = "SuperCossinLette3D"
default_targets = ["win64", "appimage", "lovejs"]
build_directory = "bin"
icon_file = "Icon.ico"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]

[lovejs]
memory = "100000000"
